### ISSUE TITLE
Add an explorer's hub topic for support

### ISSUE THREAD

**Issue by timglaser** [newrelic/nr1-vscode-extension#11]
To comply with our open source standards via the [open source checklist](https://docs.google.com/document/d/1y644Pwi82kasNP5VPVjDV8rsmkBKclQVHFkz8pwRUtE/edit), let's add an explorer's hub topic and link it in the README.

Will post something similar to what we do with the Nerdpacks which is grab some helpful bits from the README and treat it as an initial "press release" in a sense.

- Screenshot + Intro, what is it and why would you want to use it
- How to use it, install/setup 
- Link to the repo

**Example:** 
https://discuss.newrelic.com/t/announcing-a-new-relic-gatsby-site-theme/109814

**Comment by jpvajda** [comment]
https://discuss.newrelic.com/t/new-vs-code-extension-for-new-relic/111822
