### ISSUE TITLE
Nerdlife post

### ISSUE THREAD

**Issue by mbazhlekova** [newrelic/nr1-vscode-extension#22]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

Get word out about the NR1 VSCode extension!

- [ ] A Nerdlife Post

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by jpvajda** [comment]
https://nerdlife.datanerd.us/new-relic/product-accomplishment-vscode-extension-for-new-relic-8914c88f-872d-42fd-8052-0e2c859d9cac
