### ISSUE TITLE
Move the NRQL extension under the New Relic Extension Pack

### ISSUE THREAD

**Issue by mbazhlekova** [newrelic/nr1-vscode-extension#25]
Contact owner of this NRQL VSCode Extension - [NRQL VSCode Extension](https://github.com/joelalejandro/vscode-nrql-language)

Determine if he's willing to apply an open source license to his extension so we can either fork it and build on, or at least be ok with including it our extension pack.

**Comment by jpvajda** [comment]
@joelalejandro added an MIT license to the repo.
