### ISSUE TITLE
Too awesome

### ISSUE THREAD

**Issue by rdubrock** [newrelic/nr1-vscode-extension#59]
## Description
Y'all are too awesome. Can't believe you got this out so fast!

## Steps to Reproduce
Your awesomeness is not reproducible.

## Expected Behavior
Wasn't expecting such a rad vs code extension so fast.

## Relevant Logs / Console output
`ERROR: TOTALLY DOP`

## Your Environment
Full of wonder and awe

## Additional context
I'm impressed. Congrats!

**Comment by jpvajda** [comment]
@rdubrock  you are awesome for lighting the fire for this!  - hope all is well.
