### ISSUE TITLE
Extension needs an icon

### ISSUE THREAD

**Issue by fiveisprime** [newrelic/nr1-vscode-extension#76]
Hey there New Relic friends, nice extension you have here! We've featured your extension in the VS Code marketplace for this month and it looks like you could use an icon. 😄 ❤️ 

![image](https://user-images.githubusercontent.com/1186948/91612349-13ea9a00-e932-11ea-993c-acabe403a743.png)

**Comment by mbazhlekova** [comment]
Hi @fiveisprime thank you for featuring our extension! I'm able to see an icon in the marketplace. Do you mind verifying again if it's still missing?

**Comment by fiveisprime** [comment]
How strange, I wasn't seeing it on any of my devices... until I turned off my ad blocker. I'll go ahead and close this and thanks!
