### ISSUE TITLE
Add a Nerdpack Debugger feature to the extension pack

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-vscode-extension#84]
Ben has created a nerdpack debugger that he uses in VsCode and he was interested in contributing this feature to the project. 

https://marketplace.visualstudio.com/items?itemName=TanBen.vsc-nr1-debugger-extpack

**Comment by jpvajda** [comment]
@tanben If you want to make a contribution and add the nerdpack debugger you use to the new relic one extension that would be rad. Please let us know if you need any assistance contributing to this project / cc @mbazhlekova

**Comment by jpvajda** [comment]
It sounds like this is in progress...

**Comment by tanben** [comment]
PR submitted to include debugger extension, chrome and firefox debugger extension to the NR1 extension pack.
